name: Ubuntu-CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Apt Deps
      run: sudo apt update && sudo apt install -y rapidjson-dev build-essential libgl1-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 libc++abi-dev libmongoc-dev libbson-dev libgflags-dev libgoogle-glog-dev libgmock-dev libgtest-dev libopencv-dev curl cmake git wget
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
          version: 6.1.3

    - name: Download Tensorflow
      run: wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.6.0.tar.gz
      
    - name: Extract Tar
      run: sudo tar -C /usr/local -xzf libtensorflow-gpu-linux-x86_64-2.6.0.tar.gz
      
    - name: Setup Library Path
      run: sudo ldconfig
        
    - name: Download Mongodb
      run: wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
      
    - name: Add Mongo to App Sources
      run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
      
    - name: Install Mongo
      run: sudo apt update && sudo apt-get install -y mongodb-org
      
    - name: Start Mongo and Reload Daemon
      run: sudo systemctl start mongod && sudo systemctl daemon-reload
      
    - name: Download Mongodb-cxx-driver
      run: curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.6.6/mongo-cxx-driver-r3.6.6.tar.gz
   
    - name: Extract Tar
      run: tar -xzf mongo-cxx-driver-r3.6.6.tar.gz
      
    - name: Change to Build Dir
      run: cd mongo-cxx-driver-r3.6.6/build
      
    - name: Generate Build Files
      run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
      
    - name: Build Mongo Core
      run: sudo cmake --build . --target EP_mnmlstc_core
      
    - name: Build Driver
      run: cmake --build .
      
    - name: Install Driver
      run: sudo cmake --build . --target install
          
    - name: Download Open3D
      run: git clone --recursive https://github.com/intel-isl/Open3D.git
     
    - name: Change Dir & Install Deps
      run: cd Open3D/util && ./install_deps_ubuntu.sh
      
    - name: Change to Build Dir
      run: cd .. && mkdir build && cd build
      
    - name: Generate Build Files
      run: cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local ..
      
    - name: Build Open3D
      run: make -j$(nproc)
      
    - name: Install Open3D
      run: sudo make install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
