name: Ubuntu-CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Apt Deps
      run: sudo apt update && sudo apt install -y rapidjson-dev build-essential libgl1-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio++-dev libc++abi-dev libmongoc-dev libbson-dev libgflags-dev libgoogle-glog-dev libgmock-dev libgtest-dev libopencv-dev curl cmake git wget
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
          version: 6.1.3

    - name: Install Tensorflow
      run: |
          wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.6.0.tar.gz
      run: |
          sudo tar -C /usr/local -xzf libtensorflow-gpu-linux-x86_64-2.6.0.tar.gz
      run:
          sudo ldconfig
        
    - name: Install Mongodb
      run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
      run: |
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
      run: |
          sudo apt update && sudo apt-get install -y mongodb-org
      run: |
          sudo systemctl start mongod
      run:
          sudo systemctl daemon-reload

    - name: Install Mongodb-cxx-driver
      run: |
          curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.6.6/mongo-cxx-driver-r3.6.6.tar.gz
      run: |
          tar -xzf mongo-cxx-driver-r3.6.6.tar.gz
      run: |
          cd mongo-cxx-driver-r3.6.6/build
      run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
      run: |
          sudo cmake --build . --target EP_mnmlstc_core
      run: |
          cmake --build .
      run:
          sudo cmake --build . --target install
          
    - name: Install Open3D
      run: |
          git clone --recursive https://github.com/intel-isl/Open3D.git
      run: |
          cd Open3D/util
      run: |
          ./install_deps_ubuntu.sh
      run: |
          cd .. && mkdir build && cd build
      run: |
          cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local ..
      run: |
          make -j$(nproc)
      run:
          sudo make install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
