name: Ubuntu-CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Apt Deps
      run: sudo apt update && sudo apt install -y libssl-dev libsqlite3-dev rapidjson-dev build-essential libgl1-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 libgflags-dev libgoogle-glog-dev libgmock-dev libgtest-dev libopencv-dev curl cmake git wget
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
          version: 6.1.3

    - name: Download Tensorflow
      run: wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.6.0.tar.gz
      
    - name: Extract Tar
      run: sudo tar -C /usr/local -xzf libtensorflow-gpu-linux-x86_64-2.6.0.tar.gz
      
    - name: Setup Library Path
      run: sudo ldconfig
      
    - name: Install DotNet
      run: |
        wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-3.1

    - name: Install Java
      run: sudo apt install default-jre

    - name: Install P Compiler
      run: dotnet tool install --global P

    - name: Install Coyote
      run: dotnet tool install --global Microsoft.Coyote.CLI --version 1.0.5

    - name: Build P Project
      working-directory: ${{github.workspace}}/VerificationTest
      run: pc -proj:VerificationTest.pproj
      
    - name: Run Verication Test
      working-directory: ${{github.workspace}}/VerificationTest/POutput/netcoreapp3.1
      run: coyote test VerificationTest.dll -m PImplementation.tcRW.Execute

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
