name: MacOS-CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew Deps
        run: brew install mongo-c-driver cmake rapidjson glog gflags googletest libtensorflow qt gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly opencv pkg-config
        
      - name: Setup Mongo
        run: brew tap mongodb/brew
        
      - name: Install Mongo
        run: brew install mongodb-community@5.0
        
      - name: Start Mongo Service
        run: brew services start mongodb-community@5.0
      
      - name: Setup Mongodb-cxx-driver
        run: curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.6.6/mongo-cxx-driver-r3.6.6.tar.gz
        
      - name: Extract Tar
        run: tar -xzf mongo-cxx-driver-r3.6.6.tar.gz
        
      - name: Change Dir
        run: cd mongo-cxx-driver-r3.6.6/build
        
      - name: Generate Build Files
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/mongo-c-driver/lib/cmake -DCMAKE_INSTALL_PREFIX=/usr/local
        
      - name: Build Mongo Core
        run: sudo cmake --build . --target EP_mnmlstc_core
        
      - name: Build Driver
        run: cmake --build .
        
      - name: Install Driver
        run: sudo cmake --build . --target install

      - name: Setup Open3D
        run: git clone --recursive https://github.com/intel-isl/Open3D.git
        
      - name: Make Build Dir
        run: cd Open3D && mkdir build && cd build
        
      - name: Generate Build Files
        run: cmake -DBUILD_SHARED_LIBS=ON -DBUILD_GUI=OFF -DBUILD_WEBRTC=OFF DCMAKE_INSTALL_PREFIX=/usr/local ..
        
      - name: Build Open3D
        run: make -j$(sysctl -n hw.physicalcpu)
        
      - name: Install Open3D
        run: sudo make install
            
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
