name: MacOS-CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew Deps
        run: brew install mongo-c-driver cmake rapidjson glog gflags googletest libtensorflow qt gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly opencv pkg-config
        
      - name: Setup and Install Mongo
        run: |
            brew tap mongodb/brew
        run: |
            brew install mongodb-community@5.0
        run: |
            brew services start mongodb-community@5.0
      
      - name: Install Mongodb-cxx-driver
        run: |
            curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.6.6/mongo-cxx-driver-r3.6.6.tar.gz
        run: |
            tar -xzf mongo-cxx-driver-r3.6.6.tar.gz
        run: |
            cd mongo-cxx-driver-r3.6.6/build
        run: |
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/mongo-c-driver/lib/cmake -DCMAKE_INSTALL_PREFIX=/usr/local
        run: |
            sudo cmake --build . --target EP_mnmlstc_core
        run: |
            cmake --build .
        run: |
            sudo cmake --build . --target install

      - name: Install Open3D
        run: |
            git clone --recursive https://github.com/intel-isl/Open3D.git
        run: |
            cd Open3D
        run: |
            mkdir build
        run: |
            cd build
        run: |
            cmake -DBUILD_SHARED_LIBS=ON -DBUILD_GUI=OFF -DBUILD_WEBRTC=OFF DCMAKE_INSTALL_PREFIX=/usr/local ..
        run: |
            make -j$(sysctl -n hw.physicalcpu)
        run: |
            sudo make install
            
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
