name: MacOS-CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew Deps
        run: brew install ossp-uuid cmake rapidjson glog gflags googletest qt gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly opencv pkg-config sqlite3 wget
        
      - name: Build & Install OpenSSL        
        run: |
          wget --no-check-certificate https://www.openssl.org/source/openssl-3.0.0.tar.gz
          tar xf openssl-3.0.0.tar.gz
          cd openssl-3.0.0
          ./Configure
          make 
          sudo make install
      
      - name: Download Tensorflow
        run: wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-2.6.0.tar.gz
      
      - name: Extract Tar
        run: tar xf libtensorflow-cpu-darwin-x86_64-2.6.0.tar.gz
            
      - name: Copy Tensorflow to local
        run: |
          sudo cp -r include /usr/local
          sudo cp -r lib /usr/local
          
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        
      - name: Install P and Coyote
        run: |
          brew install java
          dotnet tool install --global P
          dotnet tool install --global Microsoft.Coyote.CLI --version 1.0.5
            
      - name: Build Verification Test
        working-directory: ${{github.workspace}}/VerificationTest
        run: pc -proj:VerificationTest.pproj

      - name: Run Verification Test
        working-directory: ${{github.workspace}}/VerificationTest/POutput/netcoreapp3.1
        run: coyote test VerificationTest.dll -m PImplementation.tcRW.Execute

      - name: Configure CMake
        run: cmake -DCMAKE_FIND_FRAMEWORK=LAST -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
